name: AutoCoder Workflow

on:
  issues:
    types:
      - opened
      - reopened
      - labeled

jobs:
  autocoder:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make script executable
        run: chmod +x scripts/script.sh

      - name: Generate Code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ./scripts/script.sh \
            "$GITHUB_TOKEN" \
            "$REPOSITORY" \
            "$ISSUE_NUMBER" \
            "$OPENAI_API_KEY"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact

      - name: List Artifact Contents
        run: ls -R autocoder-artifact